USE AIRS;
DROP TABLE IF EXISTS granules;
CREATE TABLE IF NOT EXISTS granules (
    processing_level STRING,
    instrument STRING,
    DayNightFlag STRING,
    AutomaticQAFlag STRING,
    NumTotalData INT,
    NumProcessData INT,
    NumSpecialData INT,
    NumBadData INT,
    NumMissingData INT,
    NumLandSurface INT,
    NumOceanSurface INT,
    node_type STRING,
    start_year INT,
    start_month INT,
    start_day INT,
    start_hour INT,
    start_minute INT,
    start_sec FLOAT,
    start_orbit INT,
    end_orbit INT,
    orbit_path INT,
    start_orbit_row INT,
    end_orbit_row INT,
    granule_number INT,
    num_scansets INT,
    num_scanlines INT,
    start_Latitude DOUBLE,
    start_Longitude DOUBLE,
    start_Time DOUBLE,
    end_Latitude DOUBLE,
    end_Longitude DOUBLE,
    end_Time DOUBLE,
    eq_x_longitude FLOAT,
    eq_x_tai DOUBLE,
    LonGranuleCen INT,
    LatGranuleCen INT,
    LocTimeGranuleCen INT,
    num_fpe INT,
    orbitgeoqa INT,
    num_satgeoqa INT,
    num_glintgeoqa INT,
    num_moongeoqa INT,
    num_ftptgeoqa INT,
    num_zengeoqa INT,
    num_demgeoqa INT,
    Rdiff_swindow_M1a_chan INT,
    Rdiff_swindow_M2a_chan INT,
    Rdiff_lwindow_M8_chan INT,
    Rdiff_lwindow_M9_chan INT,
    CF_Version STRING,
    NumSaturatedFOVs INT,
    NumUnderflowFOVs INT,
    NumCalFOVsOutOfBounds INT,
    NumSO2FOVs INT,
    granules_present STRING,
    spec_shift_y0_l1b FLOAT,
    spec_shift_dy0_l1b FLOAT,
    spec_shift_y0_l1b_nobs INT
)
COMMENT 'AIRS L1C Infrared granule info'
PARTITIONED BY (d STRING)
STORED AS PARQUET 
;
